name: CI
on: push
jobs:
  run:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [14, 15]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Run tests
        run: |
          yarn install
          yarn restapify:init
          yarn test:types
          yarn lint
          yarn test --coverage
          bash <(curl -s https://codecov.io/bash) 
